title: Pluranimity
description: >-
  Pluranimity is the personal blog of Christopher Goes.<br />
  As befitting the name, I explicitly disavow any topical continuity.<br />
  Opinions expressed herein are my own.
baseurl: ""
url: "https://pluranimity.org"
author: Christopher Goes
twitter_username: cwgoes
github_username:  cwgoes

markdown: kramdown
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
